apiVersion: v1
kind: Pod
metadata:
    namespace: edge-computing
    name: $spring_application_name
    labels:
        app: $spring_application_name
spec:
    containers:
        -   name: $spring_application_name
            image: edge-node:v2.0
            imagePullPolicy: IfNotPresent
            env:
                -   name: spring_application_name
                    value: $spring_application_name
            volumeMounts:
                -   mountPath: /root/results
                    name: data
            resources: { } 
    volumes:
        -   name: data
            nfs:
                path: /home/guohao/data/ec-data/results
                server: 222.201.187.52
    restartPolicy: Always